drop table tb_telefone;
drop table tb_endereco;
drop table tb_videogame;
drop table tb_cliente;

create table tb_cliente (
    pk_id NUMBER GENERATED by default on null as IDENTITY primary key,
    cpf varchar(11),
    nome varchar(40),
    email varchar(40)
);

create table tb_videogame (
    pk_id NUMBER GENERATED by default on null as IDENTITY primary key,
    marca varchar(11),
    modelo varchar(11),
    ano integer,
    cor varchar(20),
    desbloqueado integer,
    fk_id_cliente integer,
    CONSTRAINT fk_videogame_cliente FOREIGN KEY (fk_id_cliente) REFERENCES tb_cliente(pk_id)
);

create table tb_telefone (
    pk_id NUMBER GENERATED by default on null as IDENTITY primary key,
    numero varchar(20),
    ddd varchar(3),
    fk_id_cliente integer,
    CONSTRAINT fk_telefone_cliente FOREIGN KEY (fk_id_cliente) REFERENCES tb_cliente(pk_id)
);

create table tb_endereco (
    pk_id NUMBER GENERATED by default on null as IDENTITY primary key,
    rua varchar(20),
    numero integer,
    bairro varchar(20),
    cidade varchar(20),
    fk_id_cliente integer,
    CONSTRAINT fk_endereco_cliente FOREIGN KEY (fk_id_cliente) REFERENCES tb_cliente(pk_id)
);